---
- hosts: all 
  sudo: yes
  tasks:  
  - name: Ensure HAProxy is present
    apt: name=haproxy state=latest update_cache=yes

  - name: HAProxy configuration
    copy: src=files/haproxy.cfg dest=/etc/haproxy/ mode=755

  - name: Make sure HAProxy is enabled
    lineinfile: dest=/etc/default/haproxy regexp="ENABLED=0" line="ENABLED=1"

  - name: Ensure haproxy service start at boot
    service: name=haproxy enabled=yes

  - name: Ensure haproxy service is running
    service: name=haproxy state=started

  - name: Ensure haproxy is enabled
    service: name=haproxy enabled=yes

  - name: Ensure rsyslog is present
    apt: name=rsyslog state=present

  - name: HAProxy Log configuration
    copy: src=files/haproxy.conf dest=/etc/rsyslog.d/ mode=755 backup=no

  - name: Restart rsyslog
    service: name=rsyslog state=restarted

  - name: Configure rsyslog 1
    lineinfile: dest=/etc/rsyslog.conf line="$ModLoad imudp"

  - name: Configure rsyslog 2
    lineinfile: dest=/etc/rsyslog.conf line="$UDPServerAddress 127.0.0.1"

  - name: Configure rsyslog 3
    lineinfile: dest=/etc/rsyslog.conf line="$UDPServerRun 514"