#! /bin/sh
### BEGIN INIT INFO
# Provides: example-service
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Example Service
# Description: This file starts and stops example-service server
# 
### END INIT INFO

SERVICE_DIR=/opt/service

case "$1" in
 start)
   cd $SERVICE_DIR
   nohup $SERVICE_DIR/gradlew service-jersey-app:bootRun >> /var/log/example-service.log 2>&1 &
   ;;
 stop)
   kill -9 `cat $SERVICE_DIR/service-jersey-app/application.pid`
   sleep 10
   ;;
 restart)
   kill -9 `cat $SERVICE_DIR/service-jersey-app/application.pid`
   cd $SERVICE_DIR
   $SERVICE_DIR/gradlew service-jersey-app:bootRun >> /var/log/example-service.log 2>&1 &
   sleep 20
   ;;
 *)
   echo "Usage: example-service {start|stop|restart}" >&2
   exit 3
   ;;
esac